version: "3.7"
services:

  envoy:
    build:
      context: envoyproxy
    networks:
      - envoymesh
    expose:
      - "8001"
      - "8080"
    ports:
      - "8001:8001"
      - "8080:8080"

  extauth:
    build:
      context: authz_server
    networks:
      - envoymesh
    expose:
      - "4000"
    ports:
      - "4000:4000"

  backend:
    build:
      context: backend_server

    networks:
      - envoymesh
    expose:
      - "8123"
    ports:
      - "8123:8123"

networks:
  envoymesh: {}